### PR TITLE
Add troubleshooting content about swift errors in React Native build

### PR DESCRIPTION
**Pull request by lucasbento**
## Summary

Going through the `Getting Started` tutorial with `"react-native": "0.61.5"` makes the app crash when you build it, in order to get it working you must add a `.swift` file to the project.

## Changelog

Add troubleshooting content about swift errors in React Native build

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks so much for writing this down!

**Comment by alloy** [comment]
While this will work, how about suggesting the changes that were made in the 0.62 template instead? https://github.com/facebook/react-native/pull/27922

**Comment by priteshrnandgaonkar** [comment]
@alloy, I will do those changes in Flipper

**Comment by lucasbento** [comment]
@alloy: oh yeah, I was actually going to include screenshots but totally forgot, I'll see if I have a few minutes today to include them, should help a lot.

**Comment by lucasbento** [comment]
@alloy: screenshots added 😄

**Comment by alloy** [comment]
Perfect, thanks!

**Pull request closed without merging**
