### PR TITLE
 Concurrent Function Upgrade for Enhanced Performance 🚀

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
This pull request (PR) aims to significantly enhance the performance of the Facebook Flipper package by implementing concurrent execution of functions using the `Promise.all` feature. By leveraging the power of concurrent processing, this upgrade optimizes CPU resource utilization, resulting in improved overall efficiency.

I sincerely apologize for any mistakes or omissions that may have occurred during the implementation, and I appreciate your understanding.

**Changes Made:**
- Refactored functions to utilize `Promise.all` for concurrent execution.
- Introduced concurrent processing to maximize CPU resource utilization.

**Benefits:**
- Enhanced Performance: The introduction of concurrent execution allows multiple functions to be processed simultaneously, reducing overall execution time and boosting performance.
- Efficient CPU Resource Utilization: By leveraging concurrent processing, the PR ensures better utilization of available CPU resources, leading to improved efficiency and responsiveness.

**Additional Notes:**
Your thorough review of the changes made in this PR is greatly appreciated. Kindly provide any feedback, suggestions, or concerns you may have. Thank you for your time and consideration.

### CODE REVIEW

**Comment by passy** [comment]
This looks great! Would you mind quickly running `yarn fix` over it? There are a few minor linting problems.

**Comment by sanjaiyan-dev** [comment]
> This looks great! Would you mind quickly running `yarn fix` over it? There are a few minor linting problems.

Please accept my sincere apologies for not being able to run the `yarn lint` command. If it's not too much trouble, could you kindly assist me by executing it on my behalf or offering guidance? I am currently utilizing GitHub's cloud-based web editor. Once again, I deeply regret any inconvenience this may have caused. (@passy)

**Comment by sanjaiyan-dev** [comment]
😔

**Comment by sanjaiyan-dev** [comment]
> @passy has imported this pull request. If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47294423).

@passy Thank you so much :)

**Comment by passy** [comment]
Merged in https://github.com/facebook/flipper/commit/7cef8286f94fcd4a1f2c1e02e9be062f117949dd. Thanks again!

**Pull request closed without merging**
