### PR TITLE
Implement requestResponse for websocket connection

### PR DESCRIPTION
**Pull request by rkkautsar**
## Summary

This allow websocket client to receive and reply messages from desktop client.

## Changelog

Implement requestResponse for websocket connection, allowing websocket client to receive and reply messages from desktop client

## Test Plan

Tested with custom websocket client, allow communicating getPlugins, init, deinit, etc.
But I think it's better to have dedicated unit tests for this (currently there's none?), let me know what you think.

### CODE REVIEW

**Comment by nikoant** [comment]
cc @jknoxville

**Comment by rkkautsar** [comment]
@jknoxville You're right I think it's ok to leave out the special for `getPlugins`.Llet me change this later today

**Comment by rkkautsar** [comment]
@jknoxville I've added the special case back

**Comment by timur-valiev** [comment]
Hi! Sorry, I was out of my laptop last week.
I'm planning to get rid of getPlugins special case step-by-step, but we need it now, yes.
@jknoxville it looks good for me, ggod to merge

**Comment by jknoxville** [comment]
Great, thanks guys! Merging this now.

**Pull request closed without merging**
