### PR TITLE
Migrate away from deprecated instruments utility

### PR DESCRIPTION
**Pull request by webdevbyjoss**
## Summary

The "instruments" utility was deprecated in Xcode 12 and removed now from Xcode 13, causing all the iOS 15 / Xcode 13  builds to fail to work with Flipper.

See deprecation notice here: https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

> The instruments command is now deprecated in favor of its replacement: xctrace. Use xctrace to record, import, and export data from Instruments .trace files. (36641078)

The corresponding bug was reported here:
https://github.com/facebook/flipper/issues/2896

That call should be replaced with `xcrun xctrace` run and that is what we are doing here.

IMPORTANT: There was a workaround on killing the stale `instruments` proceses and that utility function is removed as part of this PR, as `instruments` were slow and inefficient, marked for deprecation more than a year ago. `xctrace` should not have that kind of issue and it doesn't make sense to keep this workaround now. 

## Changelog

The "instruments" call replaced with `xcrun xctrace` use, to align with deprecation introduced in Xcode 12 and offer Xcode 13 compatibility.

## Test Plan

In order to test this we should run the Flipper desktop app and make sure it connects to the Simulator started out of Xcode 13
It fails to do so in `master` version right now, see https://github.com/facebook/flipper/issues/2896

### CODE REVIEW

**Comment by passy** [comment]
This looks great! Thanks a lot for changing that. I wasn't aware of the replaced tool. We will probably need to do a bit of testing internally before shipping this.

**Comment by webdevbyjoss** [comment]
@passy can you plz give me a hint on what could be the issue with the failing tests? I'm new to the code and don't see anything in my changes that could break the build here

Tried running those locally and they fail on `master` as well, so it looks like something not related to the change we have in this PR.

**Comment by sebazelonka** [comment]
Any news on this?

**Comment by webdevbyjoss** [comment]
I'm not sure what is the process after the pull request was imported. Someone who is a Facebook employee could take a look at Phabricator and check the progress there. 

I'd say we should consider this issue as **critical**, as it blocks Flipper from being used with Xcode 13 which is the latest and greatest version right now. People from all around the world can't migrate their React Native apps to iOS 15 due to this, unless they drop Flipper for now.

**Comment by mweststrate** [comment]
We're currently testing internally, should ideally end up in tomorrows release.

**Comment by passy** [comment]
There are a few more changes we need to make. For instance, the Doctor needs to be updated to skip the `instruments` check. I hope I'll be able to do that today and then we can merge this along with the other changes. :)

**Comment by m-jachym** [comment]
image

**Pull request closed without merging**
