### PR TITLE
Update CocoaPods in Getting Started documentation

### PR DESCRIPTION
**Pull request by zvona**
## Summary
"CocoaPods / Podfile" section in "Getting Started" documentation is out of sync with Podfile provided by React Native 0.61.x. This PR updates the necessary parts of setup. In addition, it does some clarifications in code.

## Changelog

Update section "CocoaPods" in "Getting Started" documentation.

## Test Plan

These are changes in documentation. The changes can be tested by installing pods and building the project.

### CODE REVIEW

**Comment by passy** [comment]
This looks great from what I can tell (which isn't much when it comes to CocoaPods, to be frank). Thanks for the contribution. I'll leave it to @priteshrnandgaonkar to review this. :)

**Comment by priteshrnandgaonkar** [comment]
Although the current changes which you have made seems that it may work for the iOS apps. But it is worth checking out by changing the Sample App's podfile and building it, to verify if the setup works or not.

If it works then we can change the iOS integration docs along with the sample app. We plan to keep sample app as close to the documentation as possible.

**Comment by zvona** [comment]
> Thanks for the PR. I would request you to add this documentation in the RN section instead of changing it the current iOS documentation.

so the idea would be having a separate section for RN config? If so, then this can be closed for sure and I'll create a new PR with a section with correct (and tested) config.

**Comment by priteshrnandgaonkar** [comment]
> so the idea would be having a separate section for RN config? If so, then this can be closed for sure and I'll create a new PR with a section with correct (and tested) config.

Let's have a separate RN section with its installation instruction. It would be better to also have a sample app for RN which follows the installation instruction, so that users can directly tinker with it to understand the features of the flipper.

Closing this PR.

**Comment by priteshrnandgaonkar** [comment]
Looks like #567 also added the integration instruction for iOS.

**Pull request closed without merging**
