### PR TITLE
[NetworkPlugin] Fix body decode issue in Chinese character #1466

### PR DESCRIPTION
**Pull request by yaoandy107**
## Summary
Related to this [issue](https://github.com/facebook/flipper/issues/1466)

## Test Plan
I have written a minimal backend with Python Flask for testing.

Test API code: [https://gist.github.com/yaoandy107/1dc0daf2071aed0448e39100145b1ec3](https://gist.github.com/yaoandy107/1dc0daf2071aed0448e39100145b1ec3)

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks for this PR! I'll pick it up further and check if it addresses correctly all the test cases I've been gathering and won't break iOS. Might take me a while, so apologies in advance for that😅

**Comment by mweststrate** [comment]
The fix in this PR is incorrect, as it fix one specific case, but breaks others. But working on more fundamental fix so it is in progress :)

**Comment by yaoandy107** [comment]
@mweststrate Thanks for reviewing, and I'm curious about what situations will break, it look fine in mine daily work. Also, looking foward to see the final fix!

**Comment by mweststrate** [comment]
Should be fixed by https://github.com/facebook/flipper/commit/6b7b1fab5cae3adfdfab89055ec97c9ee8e8fb41 and part of next weeks release. If it isn't solved in Flipper0.64, feel free to open a fresh issue with an example URL

**Pull request closed without merging**
