### PR TITLE
Fix issue 408

### PR DESCRIPTION
**Pull request by qichuan**
Fix https://github.com/facebook/flipper/issues/408

### CODE REVIEW

**Comment by jknoxville** [comment]
Awesome, thanks for the quick submission! Looks good on the surface, but I'll review it in more depth.

**Comment by jknoxville** [comment]
Hey @qichuan the reason I haven't merged this yet is I think it will cause the initial getNodes calls to recurse all the way down the tree and end up getting every node in the view hierarchy (getNode calls updateElements, and now updateElements would call getNode on the children). At the moment, we do this lazily when each node gets expanded.
If that's true then I think a better approach would be to not add any new recursion here, but to make sure the children are updated at the top level, e.g. calling getChildren inside the INVALIDATE handler.

**Comment by qichuan** [comment]
@jknoxville Thanks for the finding, let me think about it and come back to you soon.

**Comment by qichuan** [comment]
@jknoxville So I have updated the PR with your suggestion, please take a look.

In addition, I found that the iOS Layout plugin has a similar issue, the new ViewControllers are not automatically added to the view tree, and it turns out that the invalidate message is never sent. I will create another issue for this.

**Comment by jknoxville** [comment]
Great! Many thanks @qichuan , merging it now.

**Pull request closed without merging**
