### PR TITLE
Limit request/response body to 100kb to address #457

### PR DESCRIPTION
**Pull request by EricAtPlanGrid**
## Summary

As previously reported in #457, I immediately started to see crashes with Flipper integrated due to large responses (e.g., >= 100MB). This will only write the first 100KB of the response or request body into `RequestInfo` objects.

## Changelog

- Limits request/response body in network request info to 100KB max.

## Test Plan

- Make a network request which has a response size of < 100kb, verify that it is visible in its entirety
- Make a network request w/ response size > 100kb, verify that it is truncated
- Ideally, use your application with the Network plugin running, and do not see OOMs

### CODE REVIEW

**Comment by passy** [comment]
Thanks for the PR, @EricAtPlanGrid! Would you mind signing the CLA so I can import this for internal review?

**Comment by passy** [comment]
@EricAtPlanGrid Friendly ping. :)

**Comment by EricAtPlanGrid** [comment]
@passy just waiting for legal sign off ... 😅

**Comment by EricAtPlanGrid** [comment]
Aaaand I should be all legit now, via Corporate CLA on behalf of Autodesk. I don't know if I need to do anything else here? Also, I am deeply suspicious that my change broke the build :)

cc @passy

**Comment by EricAtPlanGrid** [comment]
@passy it looks good to go now.

**Comment by EricAtPlanGrid** [comment]
@passy ping!

hi

**Comment by passy** [comment]
Sorry for the wait! Importing now. :)

**Pull request closed without merging**
