### PR TITLE
[WIP] Support for remote connections

### PR DESCRIPTION
**Pull request by yschimke**
Initial support for remote connections over plaintext websockets.  Review feedback welcome, but on for early testing.

TODO
- correct settings and icons etc
- preference to opt in to plaintext connections

### CODE REVIEW

**Comment by yschimke** [comment]
image

**Comment by yschimke** [comment]
Advice on how to setup the preferences is welcome

**Comment by yschimke** [comment]
And does the remote device type look correct?

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!

**Pull request closed without merging**
