### PR TITLE
Cleanup Flipper-Folly.podspec included headers

### PR DESCRIPTION
**Pull request by janicduplessis**
## Summary

- This removes `folly/**/*.h` in `source_files` which causes all headers to be included. Instead we include only the headers needed to build. In my case this caused a conflict with folly's "Zlib.h" getting included instead of the system "zlib.h" (apparently paths are not case sensitive).
- Remove duplicates in `public_header_files`, we can just keep `"folly/**/*.h"` to make all headers public.
- Remove `preserve_paths`, this is not be needed anymore.

## Changelog

Cleanup Flipper-Folly.podspec included headers

## Test Plan

Tested in an app that everything build using the modified podspec.

### CODE REVIEW

**Comment by priteshrnandgaonkar** [comment]
I tried building the sample app with this changes, but it failed. 

Screen Shot 2019-08-22 at 2 54 36 PM

**Comment by janicduplessis** [comment]
Oh strange, I'll try testing using the sample app.

**Comment by janicduplessis** [comment]
I was able to run the Sample app successfully on a fresh repo clone. Did you update pods before running it? Maybe also try cleaning everything too.

**Comment by priteshrnandgaonkar** [comment]
Apologies for late reply. @janicduplessis, Yupp I updated the pods and also ran it after cleaning the repo. How did you test it ? The sample app doesn't locally refer to the Flipper-Folly.podspec. I replaced the Folly podspec in  `~/.cocoapods/repos/`  with your podspec and it failed.

**Comment by birkir** [comment]
Flipper is currently breaking react-native builds, hoping to get this merged, as this is the potential fix.

**Comment by priteshrnandgaonkar** [comment]
I will have a look at it by tomorrow.

**Comment by priteshrnandgaonkar** [comment]
This changes cause the following errors when I build Sample app

```
Ld /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Sample.app/Sample normal x86_64 (in target 'Sample' from project 'Sample')
    cd /Users/prit91/fbsource/xplat/sonar/iOS/Sample
    /Applications/Xcode_11.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-ios9.0-simulator -isysroot /Applications/Xcode_11.2.1_fb.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/ComponentKit -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/DoubleConversion -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Flipper -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Flipper-Folly -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Flipper-PeerTalk -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Flipper-RSocket -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/FlipperKit -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Yoga -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/YogaKit -L/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/glog -L/Users/prit91/fbsource/xplat/sonar/iOS/Sample/Pods/CocoaLibEvent/lib -L/Users/prit91/fbsource/xplat/sonar/iOS/Sample/Pods/OpenSSL-Universal/ios/lib -F/Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator -filelist /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Intermediates.noindex/Sample.build/Debug-iphonesimulator/Sample.build/Objects-normal/x86_64/Sample.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Intermediates.noindex/Sample.build/Debug-iphonesimulator/Sample.build/Objects-normal/x86_64/Sample_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode_11.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Intermediates.noindex/Sample.build/Debug-iphonesimulator/Sample.build/Objects-normal/x86_64/Sample.swiftmodule -ObjC -lCocoaAsyncSocket -lComponentKit -lDoubleConversion -lFlipper -lFlipper-Folly -lFlipper-PeerTalk -lFlipper-RSocket -lFlipperKit -lYoga -lYogaKit -lc++ -lcrypto -levent -levent_core -levent_extra -levent_pthreads -lglog -lssl -lstdc++ -framework CFNetwork -framework CoreText -framework Security -framework UIKit -ObjC -lc++ -lglog -lstdc++ -framework CFNetwork -framework CoreText -framework Security -framework UIKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Intermediates.noindex/Sample.build/Debug-iphonesimulator/Sample.build/Sample.app-Simulated.xcent -lPods-Sample -Xlinker -dependency_info -Xlinker /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Intermediates.noindex/Sample.build/Debug-iphonesimulator/Sample.build/Objects-normal/x86_64/Sample_dependency_info.dat -o /Users/prit91/Library/Developer/Xcode/DerivedData/Sample-axzhkrugaywwcdexusrzbmmdokos/Build/Products/Debug-iphonesimulator/Sample.app/Sample

Undefined symbols for architecture x86_64:
  "_rallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(IOBuf.o)
      ...
  "_mallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::threadlocal_detail::StaticMetaBase::reallocate(folly::threadlocal_detail::ThreadEntry*, unsigned int, unsigned long&) in libFlipper-Folly.a(ThreadLocalDetail.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      ...
  "_xallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::threadlocal_detail::StaticMetaBase::reallocate(folly::threadlocal_detail::ThreadEntry*, unsigned int, unsigned long&) in libFlipper-Folly.a(ThreadLocalDetail.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      ...
  "_sallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(IOBuf.o)
      ...
  "_dallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(IOBuf.o)
      ...
  "_mallctlbymib", referenced from:
      folly::detail::MemoryIdler::flushLocalMallocCaches() in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      ...
  "_sdallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(IOBuf.o)
      ...
  "_nallocx", referenced from:
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::goodMallocSize(unsigned long) in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::goodMallocSize(unsigned long) in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::goodMallocSize(unsigned long) in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      ...
  "_mallctl", referenced from:
      folly::detail::MemoryIdler::flushLocalMallocCaches() in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      void folly::detail::mallctlHelper<unsigned int>(char const*, unsigned int*, unsigned int*) in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      ...
  "_mallctlnametomib", referenced from:
      folly::detail::MemoryIdler::flushLocalMallocCaches() in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(MemoryIdler.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(Format.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(EventBase.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper.a(FlipperConnectionManagerImpl.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ExceptionWrapper.o)
      folly::usingJEMalloc()::'lambda'()::operator()() const in libFlipper-Folly.a(ThreadLocalDetail.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by priteshrnandgaonkar** [comment]
I added following line to the `spec.source_files` and it solved the issues with the compilation of the sample objc app. I also confirmed that the sample swift app builds successfully.

```
"folly/memory/detail/*.cpp"
```

Once you add the above changes, I will merge this and make a new Flipper-Folly release on cocoapods.

**Comment by janicduplessis** [comment]
Thanks, for figuring out the issue, I didn’t have time to follow up on this. I updated the PR with the change you suggested.

**Pull request closed without merging**
