### PR TITLE
Update databases-plugin.md

### PR DESCRIPTION
**Pull request by mateosilguero**

### CODE REVIEW

**Comment by passy** [comment]
Thanks for catching this!

**Comment by passy** [comment]
@mateosilguero Apologies but I'm not quite sure how to understand that reaction on the message. :) Unfortunately, I can't merge this unless you sign that waiver.

**Comment by mateosilguero** [comment]
Sorry, i just signed the cla.

**Comment by passy** [comment]
Brilliant. Thanks a lot for the fixes. Please keep them coming. :)

**Pull request closed without merging**
