### PR TITLE
Fix: Release builds on android

### PR DESCRIPTION
**Pull request by b3coded**
## Summary

After `react-native-flipper` 0.48.0 I cannot build releases on android (I think that passed on CI tests because the example was running an older version of this package, 0.47.0).
So I moved all the `android/src/main` content to `android/src/debug` because we will not use Flipper in another Build Variant

## Changelog

I moved all content from `react-native-flipper/android/src/main` to `react-native-flipper/android/src/debug`.

Probably solves #1303 

## Test Plan

Maybe create a custom CI script to verify if Flipper deps are present on Release Builds, [something like this](https://github.com/facebook/flipper/issues/1274#issue-641197153)

### CODE REVIEW

**Comment by passy** [comment]
You're a star! Thank you.

**Comment by TheAlmightyBob** [comment]
I applied this change locally and the build still failed due to `PackageList` being unable to find `FlipperPackage`

**Comment by b3coded** [comment]
> I applied this change locally and the build still failed due to `PackageList` being unable to find `FlipperPackage`

@passy can I add one more commit? I forgot to add a `FlipperPackage.java` inside `main` folder.
Will solve this problem

**Comment by b3coded** [comment]
@passy The error still persists, I asked on ReactNative CLI repo [here](https://github.com/react-native-community/cli/issues/1211) but the answer was not positive :disappointed:

**Pull request closed without merging**
