### PR TITLE
Use interface SupportSQLiteDatabase in Android Databases Plugin

### PR DESCRIPTION
**Pull request by aartikov**
## Summary
This change will allow to use various SQLiteDatabase implementations: standard Android implementation, [requery/sqlite-android](https://github.com/requery/sqlite-android) and so on. See issue #1183 

## Changelog
Android Databases Plugin: `SqliteDatabaseConnectionProvider` returns `SupportSQLiteDatabase` instead of `SQLiteDatabase`.

## Test Plan
Check that Databases Plugin shows correct data on the sample Android application.

### CODE REVIEW

**Comment by passy** [comment]
This looks great! Thanks for doing this. I'll import this for internal review.

**Comment by aartikov** [comment]
@passy I have added some fixes. Please, import it again.

**Comment by passy** [comment]
@aartikov Really sorry for the wait. Do you know where `androidx.sqlite.db.framework.FrameworkSQLiteDatabaseWrapping` is coming from or when it was added? This is failing to resolve internally.

**Comment by aartikov** [comment]
@passy It is a part of the pull request https://github.com/facebook/flipper/pull/1196/files#diff-6deeccf2669d9a45af844801f3979441
I placed it to `androidx.sqlite.db.framework` to get access to package-private class `FrameworkSQLiteDatabase`.

**Comment by passy** [comment]
@aartikov Oh, I didn't see that at first. Sorry, I'm afraid we can't ship with that. This doesn't work well with our build system and it's generally not a good form to publish artifacts into someone else's namespace.

**Comment by passy** [comment]
@aartikov Do you think reflection would be an option here at all? It may seem a little ugly, but it would help with compatibility here.

**Comment by aartikov** [comment]
@passy Yes, we can use reflection here. I have pushed this change.

**Comment by aartikov** [comment]
@passy could you please review it?

**Comment by passy** [comment]
@aartikov Apologies for the delay! I'm a little swamped right now, but I'll take a look this week.

**Comment by likern** [comment]
@aartikov Hello, not sure my problem is the same.

But when I open flipper and try to refresh database - it looks like database **is completely deleted** (I suggest by flipper itself).
Also I can sometimes see database itself, but never tables (emtpy popup list).

I use React Native with https://github.com/breeffy/mobbly/commit/86813c1f4bab7e1b1719bea0aa86b416c5937391 which itself uses https://github.com/requery/sqlite-android.

I tried your patch (I hoped it's related, but not sure). Didn't help to fix my problem.

**Pull request closed without merging**
