### PR TITLE
Producing new state when any change to preferences happen to address #470

### PR DESCRIPTION
**Pull request by umasankar-yedida**
## Summary

Fixed issue #470 

## Changelog

Producing new state when preferences gets updated in SharedPreferences plugin

### CODE REVIEW

**Comment by jknoxville** [comment]
Thanks for the contribution @umasankar-yedida 
Perhaps we should for pragmatism but I'm a little bit hesitant to merge as this seems to be hiding the issue of the DataInspector not getting re-rendered when it should be.
However, I've spent some time looiking into it and I'm still not sure why that is. @umasankar-yedida or @mweststrate do you know what's going on here?

**Comment by mweststrate** [comment]
The problem here is not in the DataInspector (this change would kill most optimizations for all consumers of that component!). The problem is in the reducers of the shared preferences plugin, which does not produce new state, but rather modifies it's current state: 

https://github.com/facebook/flipper/blob/6e8de457e7882ad51de1e44ad9fa9d82ece2fa75/src/plugins/shared_preferences/index.js#L94-L121

I'd expect making the following change fixes the problem (sorry, I am not sure yet how to test that change :)) 

```
    UpdateSharedPreferences(state: SharedPreferencesState, results: Object) {
      const update = results.update;
      const entry = state.sharedPreferences[update.name] || {changesList: []};
      entry.preferences = update.preferences;
      // don't mutate the current state!
      return {
         ...state,
         selectedPreferences: state.selectedPreferences || update.name,
         sharedPreferences: {
             ...state.sharedPreferences,
            [update.name] = entry;
         }
      }
    },

    ChangeSharedPreferences(state: SharedPreferencesState, event: Object) {
      const change = event.change;
      const entry = state.sharedPreferences[change.preferences];
      if (entry == null) {
        return state;
      }
      let newEntry
      if (change.deleted) {
        const newPreferences = {...entry.preferences }
        delete newPreferences[change.name]
        newEntry = { ...entry, preferences: newPreferences }
      } else {
        newEntry = { ...entry, preferences: { ...entry.preferences, [change.name] : change.value } };
      }
      newEntry.changesList = [change, ...entry.changesList];
      return {
        ...state,
        sharedPreferences: {
            ...state.sharedPreferences,
            [change.preferences] = newEntry
        }
      };
    },
```

**Comment by umasankar-yedida** [comment]
From the issue, I understood that the props are not getting updated in `ManagedDataInspector` component as this is acting as a wrapper to the `DataInspector` component.

**Comment by umasankar-yedida** [comment]
@mweststrate I tried your approach and it worked !!! Thanks man. :)

**Pull request closed without merging**
